package model;

public enum Role {
    PROJECT_MANAGER,
    PRODUCT_OWNER,
    TEAM_LEAD,
    TECH_LEAD,
    FULL_STACK_DEVELOPER,
    FRONT_END_DEVELOPER,
    BACK_END_DEVELOPER,
    QA_LEAD,
    QA_ENGINEER,
    TESTER,
    UI_DESIGNER,
    UX_DESIGNER
}
